"""
Django settings for MeuSite project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-=ebr^oj$j2nlst0cu0bqqz$^oh=^80ut$0bew8nxh=02d&9pq&"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']       # esta variável já existia mas o valor estava errado. Troquei o valor para '*' para permitir acesso de qualquer host, o que é útil durante o desenvolvimento. Em produção, você deve especificar os hosts permitidos.
CORS_ALLOW_ALL_ORIGINS = True   # esta variável não existia, mas é necessária para permitir que o frontend (que pode estar rodando em um host diferente) acesse a API do backend. Definir como True permite todas as origens, o que é útil durante o desenvolvimento. Em produção, você deve configurar isso de forma mais restritiva.
CSRF_TRUSTED_ORIGINS = [        # esta variável tambem não exitia, tive que criar. Ela é necessária para permitir que o backend aceite requisições de origens confiáveis, especialmente quando o frontend e o backend estão em hosts diferentes. Adicionei os hosts locais comuns para desenvolvimento.
    'https://localhost:8000', 
    'http://localhost:8000',
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'MeuSite',
    'curriculo',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "MeuSite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "MeuSite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# ---------
# Código que eu precisei incluir
# ---------

LOGOUT_REDIRECT_URL = '/accounts/login/'  # Para onde vai após logout
LOGIN_URL = '/accounts/login/'       # URL de login (padrão)
# ATENÇÃO!!! Troque o valor da variável abaixo para que ela seja uma das rotas
# válidas no seu arquivo MeuSite/curriculo/urls.py
LOGIN_REDIRECT_URL = '/'   # Para onde vai após login
